A power B 
Given 2 numbers - A and B, evaluate AB.



Note:

Do not use any inbuilt functions / libraries for your main logic.



Input Format
The first line of input contains T - the number of test cases. It's followed by T lines, each line containing 2 numbers - A and B, separated by space.



Output Format

For each test case, print AB, separated by new line. Since the result can be very large, print result % 1000000007



Constraints

30 points

1 <= T <= 1000

0 <= A <= 106

0 <= B <= 103



70 points

1 <= T <= 1000

0 <= A <= 106

0 <= B <= 109



Example

Input

4

5 2

1 10

2 30

10 10



Output

25

1

73741817

999999937



Explanation



Self Explanatory



#include <bits/stdc++.h>
using namespace std;

long pown(long b,long c){
    if(c==1) return b;
    if(c==0) return 1;
    long p=pown(b,c/2)%1000000007;
    if (c%2==0) return (p*p)%1000000007;
    else return (b*p)%1000000007*p%1000000007;
}
int main() {
    long a;
    scanf("%ld",&a);
    while(a--){
        long b,c;
        scanf("%ld %ld",&b,&c);
        printf("%ld\n",pown(b,c)%1000000007);
    }
    return 0;
}